services:
  frigate-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frigate-telegram-bot
    env_file:
      - .env
    network_mode: host
    restart: unless-stopped
